"""Trade data models"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional
from decimal import Decimal


class AssetType(Enum):
    CRYPTO = "crypto"
    GOLD = "gold"


class WalletType(Enum):
    PAPER = "paper"   # กระเป๋าตังจำลอง — ไม่ใช้เงินจริง
    LIVE = "live"      # กระเป๋าตังจริง — เทรดด้วยเงินจริง


class TradeDirection(Enum):
    BUY = "buy"
    SELL = "sell"


class TradeStatus(Enum):
    PENDING = "pending"
    OPEN = "open"
    CLOSED = "closed"
    CANCELLED = "cancelled"


@dataclass
class TradeSignal:
    """Signal generated by AI for trading decision"""
    asset_type: AssetType
    symbol: str
    direction: TradeDirection
    entry_price: float
    quantity: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    confidence: float = 0.0
    reasoning: str = ""
    wallet_type: WalletType = WalletType.PAPER  # ระบุว่าสัญญาณนี้ใช้กระเป๋าตัง哪种
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class Trade:
    """Individual trade record"""
    id: Optional[int] = None
    symbol: str = ""
    asset_type: AssetType = AssetType.CRYPTO
    wallet_type: WalletType = WalletType.PAPER  # แยกกระเป๋าตังจาก PAPER หรือ LIVE
    direction: TradeDirection = TradeDirection.BUY
    entry_price: float = 0.0
    exit_price: Optional[float] = None
    quantity: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    status: TradeStatus = TradeStatus.PENDING
    entry_time: Optional[datetime] = None
    exit_time: Optional[datetime] = None
    trade_number: int = 0  # ไม้ที่เท่าไหร่
    
    @property
    def pnl(self) -> Optional[float]:
        """Calculate P&L in quote currency"""
        if self.exit_price is None:
            return None
        if self.direction == TradeDirection.BUY:
            return (self.exit_price - self.entry_price) * self.quantity
        else:  # SELL
            return (self.entry_price - self.exit_price) * self.quantity
    
    @property
    def pnl_percent(self) -> Optional[float]:
        """Calculate P&L percentage"""
        if self.exit_price is None or self.entry_price == 0:
            return None
        if self.direction == TradeDirection.BUY:
            return ((self.exit_price - self.entry_price) / self.entry_price) * 100
        else:
            return ((self.entry_price - self.exit_price) / self.entry_price) * 100


@dataclass
class TradeResult:
    """Summary of trading session"""
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    total_pnl: float = 0.0
    win_rate: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    
    def calculate_metrics(self):
        """Calculate derived metrics"""
        if self.total_trades > 0:
            self.win_rate = (self.winning_trades / self.total_trades) * 100
        if self.winning_trades > 0:
            self.avg_win = self.total_pnl / self.winning_trades
        if self.losing_trades > 0:
            self.avg_loss = abs(self.total_pnl) / self.losing_trades if self.total_pnl < 0 else 0


@dataclass
class Wallet:
    """Wallet — separate balance for PAPER or LIVE trading"""
    wallet_type: WalletType
    balance: float
    currency: str = "USDT"
    initial_balance: float = 0.0

    def __post_init__(self):
        if self.initial_balance == 0.0:
            self.initial_balance = self.balance

    @property
    def pnl(self) -> float:
        """Total P&L vs initial balance"""
        return self.balance - self.initial_balance

    def to_dict(self) -> dict:
        return {
            "wallet_type": self.wallet_type.value,
            "balance": round(self.balance, 2),
            "currency": self.currency,
            "initial_balance": round(self.initial_balance, 2),
            "pnl": round(self.pnl, 2),
        }
